In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv
from numpy import mean
from sklearn.metrics import mean_squared_error

In [5]:
series = read_csv('../Docs/daily-total-female-births.csv', header=0, index_col=0)
# prepare situation
X = series.values
window = 3
history = [X[i] for i in range(window)]
test = [X[i] for i in range(window, len(X))]
predictions = list()

In [15]:
series.head(20)

Births
Date              
1959-01-01      35
1959-01-02      32
1959-01-03      30
1959-01-04      31
1959-01-05      44
1959-01-06      29
1959-01-07      45
1959-01-08      43
1959-01-09      38
1959-01-10      27
1959-01-11      38
1959-01-12      33
1959-01-13      55
1959-01-14      47
1959-01-15      45
1959-01-16      37
1959-01-17      50
1959-01-18      43
1959-01-19      41
1959-01-20      52

In [16]:
X[:10]

array([[35],
       [32],
       [30],
       [31],
       [44],
       [29],
       [45],
       [43],
       [38],
       [27]])

In [17]:
history

[array([35]), array([32]), array([30])]

In [18]:
test

[array([31]),
 array([44]),
 array([29]),
 array([45]),
 array([43]),
 array([38]),
 array([27]),
 array([38]),
 array([33]),
 array([55]),
 array([47]),
 array([45]),
 array([37]),
 array([50]),
 array([43]),
 array([41]),
 array([52]),
 array([34]),
 array([53]),
 array([39]),
 array([32]),
 array([37]),
 array([43]),
 array([39]),
 array([35]),
 array([44]),
 array([38]),
 array([24]),
 array([23]),
 array([31]),
 array([44]),
 array([38]),
 array([50]),
 array([38]),
 array([51]),
 array([31]),
 array([31]),
 array([51]),
 array([36]),
 array([45]),
 array([51]),
 array([34]),
 array([52]),
 array([47]),
 array([45]),
 array([46]),
 array([39]),
 array([48]),
 array([37]),
 array([35]),
 array([52]),
 array([42]),
 array([45]),
 array([39]),
 array([37]),
 array([30]),
 array([35]),
 array([28]),
 array([45]),
 array([34]),
 array([36]),
 array([50]),
 array([44]),
 array([39]),
 array([32]),
 array([39]),
 array([45]),
 array([43]),
 array([39]),
 array([31]),
 array([27]),
 array

In [21]:
for t in range(len(test[:10])):
    length = len(history)
    yhat = mean([history[i] for i in range(length-window,length)])
    obs = test[t]
    
    print(length)
    print(yhat)
    print(obs)

3
32.333333333333336
[31]
3
32.333333333333336
[44]
3
32.333333333333336
[29]
3
32.333333333333336
[45]
3
32.333333333333336
[43]
3
32.333333333333336
[38]
3
32.333333333333336
[27]
3
32.333333333333336
[38]
3
32.333333333333336
[33]
3
32.333333333333336
[55]
